### ISSUE TITLE
Add Registry/Catalog/Monitor Arch Diagrams

### ISSUE THREAD

**Issue by mwengren** [ioos/catalog#19]
Add relevant architecture diagrams to the GitHub Pages docs for Catalog.  

Pages: 
- https://ioos.github.io/catalog/pages/architecture/ : Overview
- https://ioos.github.io/catalog/pages/architecture/registry/: Harvest Registry
- https://ioos.github.io/catalog/pages/architecture/data_catalog/: Data Catalog
- https://ioos.github.io/catalog/pages/architecture/monitor/: Service Monitor

**Comment by mwengren** [comment]
![future_ioos_service_registry_catalog](https://cloud.githubusercontent.com/assets/1469921/20755391/cf6bc3e4-b6dc-11e6-87aa-7b876339cff2.png)

**Comment by benjwadams** [comment]
@mwengren , is that diagram editable?  Looks pretty good, but I have a couple of things to mention here:

The central WAF should probably be data.ioos.us/waf now.  Also perhaps use a different icon because it's a WAF, not technically a database.

Probably should have the CKAN harvester processes in between the central WAF and the CKAN instance.

Fairly optional, but the current architecture has both the CKAN and the PyCSW databases residing on the same database cluster, so perhaps group them together in the same box.

Lastly, the service monitor has its own harvester processes which grab data from the CKAN API.  While this functionality is technically exposed the the end-user, conceptually I see the API as separate from the UI components in CKAN for searching the datasets, etc, so perhaps it also belongs in its own box.

**Comment by mwengren** [comment]
@benjwadams The source for the diagram was @lukecampbell... hopefully he can get you an editable copy.  

As far as the central WAF location, we are still using registry.ioos.us I believe.  This is where the Harvest Registry writes out metadata for CKAN to harvest from: https://registry.ioos.us/waf/.

Open to suggestions on other changes.  It's a lot to show in one diagram, so it would be best to not overcomplicate, but we still want to be accurate.  (Like for instance I don't know if it's worth distiguishing between the CKAN web interface and the API for Service Monitor harvesting).  All depends on how it ends up looking.

**Comment by lukecampbell** [comment]
Correct, the central WAF is registry.ioos.us/waf/ 

I realize there's some confusion there because we used to have the central WAF in a different place on data.ioos.us. Since the central WAF is created by the registry and is part of the registry, it made sense to put the central WAF on registry.ioos.us.

**Comment by lukecampbell** [comment]
![ioos service registry and catalog](https://cloud.githubusercontent.com/assets/1155163/21644837/814ffc92-d25d-11e6-9bb5-19e9e5bda2fe.png)
