### ISSUE TITLE
Mismatch between service links and metadata links

### ISSUE THREAD

**Issue by dpsnowden** [ioos/catalog#324]
See http://catalog.ioos.us/services/52603b208c0db35c6a0855fc for an example.  

The data info and data access URLs both point to a THREDDS server.  The metadata URL points to an ISO document published by ERDDAP.  I'm not sure how this happened but it is misleading.  The metadata document from ERDDAP almost certainly doesn't point to the THREDDS server.  This is why we need ISO from both THREDDS and ERDDAP for each deployment on the glider dac.  I'm not sure how it's done through the RAs but it may reflect a registration error.  We need to keep ERDDAP separate from THREDDS in the registration, even if it's almost the same data set.

**Comment by benjwadams** [comment]
Per Derrick's original post, it seems that ERDDAP links were in the original CSW request along with the THREDDS endpoints.  I've made it so that it'll only use an ERDDAP metadata endpoint if the url is itself an ERDDAP endpoint and otherwise try to get a standard DAP distrubution.  I checked today and the 'scheme' was not using the ERDDAP descriptor, so I still have to go by what's in the URL to differentiate between DAP (non-ERDAP), ERDDAP, and non-DAP sources.
