### ISSUE TITLE
Push to have harvesting scripts on github

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/catalog#34]
Could we push to get WAF ISO harvesting scripts posted here?  
Currently we only have  neracoos:
https://github.com/ioos/catalog/tree/master/waf_generation_scripts

I ask because the current harvest of MARACOOS forecast data from espressso populating this WAF
http://tds.maracoos.org/iso/
has an issue, and I know how to solve it (#31 (comment)) , and if the code were posted, I could just submit a PR.

**Comment by benjwadams** [comment]
@rsignell-usgs :  I honestly haven't looked at the individual scripts these days because they mostly seem to just work.  Nonetheless, there appear to be scripts for a few more institutions since this issue was originally posted.   Is the current state of the scripts posted sufficient to close out this issue?

**Comment by benjwadams** [comment]
Harvester scripts have been updated and pushed  to GitHub.  Closing.
