### ISSUE TITLE
Investigate CO-OPS/NDBC SOS harvesting failures

### ISSUE THREAD

**Issue by benjwadams** [ioos/catalog#360]
COOPS and NDBC SOS services are not being harvested properly, mentioned initially in #318.  So far my preliminary attempts at debugging the problem have led me to believe it is related to how the SOS response is formatted.

**Comment by benjwadams** [comment]
One issue here is that COOPS and NDBC have `text/xml;subtype="sensorML"`  listed as the `outputFormat` rather than `text/xml;subtype="sensorML/1.0.1/profiles/ioos_sos/1.0"`, which catalog tries to pass it.  This is one facet of the problem.

**Comment by dpsnowden** [comment]
The coops and NDBC sos servers don't implement the IOOS profile. We need special handlers for those two. See the pyoos collectors for details. 

Cheers,
Derrick

Sent from my phone. Please excuse my brevity. 




On Fri, Feb 13, 2015 at 6:58 AM -0800, "benjwadams" <notifications@github.com> wrote:












One issue here is that COOPS and NDBC have text/xml;subtype="sensorML"  listed as the outputFormat rather than text/xml;subtype="sensorML/1.0.1/profiles/ioos_sos/1.0", which catalog tries to pass it.  This is one facet of the problem.

**Comment by benjwadams** [comment]
Aye, I'm aware.  I think an OWSLib SOS object is being used currently instead of a Pyoos collector.  After setting the correct `outputFormat`, it bombs since it doesn't conform to the IOOS profile.

**Comment by lukecampbell** [comment]
I'm checking it on production right now, if it's harvesting successfully, I will close this issue.

**Comment by lukecampbell** [comment]
![screen shot 2015-03-13 at 9 07 47 am](https://cloud.githubusercontent.com/assets/1155163/6638859/82e0943e-c960-11e4-9713-42cd9525a943.png)
![screen shot 2015-03-13 at 9 08 04 am](https://cloud.githubusercontent.com/assets/1155163/6638863/86c8582a-c960-11e4-83a4-15e43a37ad78.png)

**Comment by carmelortiz** [comment]
Validated fix. Checked today and NDBC harvested successfully last 18 of 20 times, CO-OPS successful last 17 of 20.
