### ISSUE TITLE
Display only unique datasets?

### ISSUE THREAD

**Issue by lukecampbell** [ioos/catalog#376]
The front landing page indicates over 17k datasets which is partially due to the fact that some RAs are sharing datasets. 

This issue will track progress towards the goal of only showing the unique number of datasets within IOOS Catalog.

**Comment by lukecampbell** [comment]
@dpsnowden

**Comment by dpsnowden** [comment]
When will we be able to see the updated page? How many duplicates were there? I ask because I'd like us to think about how we refer people back to the source of the data. In the case of duplicate data what is the source? Can we define an order of precedence?

Cheers,
Derrick

Sent from my phone. Please excuse my brevity. 




On Wed, Mar 18, 2015 at 10:58 AM -0700, "Luke Campbell" <notifications@github.com> wrote:












Closed #376 via #377.
