### ISSUE TITLE
Unharvestable CeNCOOS Services

### ISSUE THREAD

**Issue by robragsdale** [ioos/catalog#395]
@jpatterson @bochenek there are a number of DAP services being reported as down in the catalog monitor.  They are not being harvested successfully.  Here is the [list](http://catalog.ioos.us/services/filter/CeNCOOS/DAP) of CeNCOOS services from the Catalog monitor page and status.  Are you experience any issues with your server that might be resulting in these unharvestable services?

**Comment by shane-axiom** [comment]
@jpatterson can confirm but I think all of the www.cencoos.org datasets should be removed.

The problematic services hosted on thredds.axiomalaska.com and thredds.axiomdatascience.com (and actually all thredds.axiomalaska.com should be changed to thredds.axiomdatascience.com) I believe are all just taking more than the allotted 60 seconds to cold load the DAP page/endpoint due to their size.

**Comment by lukecampbell** [comment]
If you could coordinate that at https://github.com/ioos/registry/issues and have them update the Geoportal instance, that would be good.

**Comment by susoson** [comment]
@robragsdale The www.cencoos.org THREDDS services are no longer active, please remove them from the IOOS catalog.

**Comment by shane-axiom** [comment]
[Issue to remove inactive services](https://github.com/ioos/registry/issues/78) is progressing on the registry repo, this can be closed.
