### ISSUE TITLE
Harvest OceanSITES metadata as a test case for new harvest registry.  See oceansites/dmt#16

### ISSUE THREAD

**Issue by dpsnowden** [ioos/catalog#8]
See oceansites/dmt#16

**Comment by mwengren** [comment]
I'm trying to revisit a lot of these loose end harvesting tasks for the Catalog at the moment.  OceanSITES was never harvested for the initial Catalog release.

@dpsnowden do you know whether OceanSITES publishes their own WAF?  I looked around the website but didn't see anything.  If not, we will probably need to set up our own process to maintain one on data.ioos.us (similar to what we do now for NDBC and CO-OPS SOS services).

This would be THREDDS/ncISO however.  Should we be harvesting from [this](http://dods.ndbc.noaa.gov/thredds/catalog/oceansites/catalog.html) THREDDS server?  If so, we may be able to ask NDBC to generate a WAF for us presumably?  I don't know the relationship between NDBC and OceanSITES or if this would be a reasonable ask. 

I am planning to ask them to do this for the HF Radar DAC and their SOS, since we've been maintaining these for them the past year,  so if so we can ask at once.  cc @kbailey-noaa.

**Comment by dpsnowden** [comment]
I don't think we should focus on OceanSITES at the moment, or, if we do we should just look at the DATA_GRIDDED directory and not the DATA directory.  There are still 12000 records in DATA and I'm not sure it's worth the cycle time at this point to regularly reharvest 12000 records.

Suggest leaving this on the way back burner and moving it back to the icebox.  The OceanSITES DMT has not weighed in on the need for this and whether or not they can provide support.

**Comment by mwengren** [comment]
Ok, officially moved to back burner status again.  

For future reference, focus should be on harvesting from DATA_GRIDDED catalog (http://dods.ndbc.noaa.gov/thredds/catalog/oceansites/DATA_GRIDDED/catalog.html).

**Comment by mwengren** [comment]
Closing due to no action on identified data sources.  If we have a need for OceanSITES data in the future we can revisit.
