### ISSUE TITLE
Fix MARACOOS Logo

### ISSUE THREAD

**Issue by kknee** [ioos/catalog#81]
Showing as a broken link for me: https://data.ioos.us/organization/maracoos

**Comment by mwengren** [comment]
Currently, Catalog points to this URL to grab the MARACOOS logo:

https://pbs.twimg.com/profile_images/1384705096/MARACOOS_round_transparent.png

Seems this must have changed since we set these Orgs up.  Here's a good replacement from the current homepage: 

https://maracoos.org/images/logo.png

I can fix this right now....
